before:
  hooks:
    - make build
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'github.com/amir20/eztv-watcher/cmd.version={{.Version}}'
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapcraft:
  publish: true
  summary: eztv-watcher is a command line utility which monitors shows on eztv and downloads torrents to a desired directory.
  description: |
    eztv-watcher is a command line utility which monitors shows on eztv and downloads torrents to a desired directory.
  grade: stable
  confinement: strict
  apps:
    eztv-watcher:
      plugs: ["home", "network", "removable-media"]

dockers:
  - image_templates:
      - "amir20/eztv-watcher:{{ .Tag }}"
      - "amir20/eztv-watcher:v{{ .Major }}.{{ .Minor }}"
      - amir20/eztv-watcherdozzle:latest
