// +build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

func main() {
	bytes, err := ioutil.ReadFile("conf/config.yml")
	die(err)

	f, err := os.Create("config_generated.go")
	die(err)
	defer f.Close()

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		Config    []byte
	}{
		Timestamp: time.Now(),
		Config:    bytes,
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package main

var ConfigFileTemplate = []byte({{ printf "%q" .Config }})
`))
